### ISSUE TITLE
When compile_check not set

### ISSUE THREAD

**Issue by treblacy** [mustafaquraish/marker#5]
When compile_check is not set in config.yml, reports include this message:

"There were errors in compiling your submission and no executable could be 
produced. No points will be assigned to you. If you think this is a mistake, 
please contact us."

(Apart from that, test cases run fine, marks are given correctly.)

**Comment by mustafaquraish** [comment]
Already fixed in [this commit](https://github.com/mustafaquraish/marker/commit/9aeac55362d96b259e06c63f5ab9f92ea658f058). Just trying not to update the `pypi` release too often. Still polishing up some minor things so will push a new release with all of them soon.
